add imagic

diff --git a/php/Dockerfile b/php/Dockerfile
--- a/php/Dockerfile
+++ b/php/Dockerfile
@@ -15,5 +15,31 @@ RUN apt-get update; \
     apt-get install -y libmagickwand-dev; \
     pecl install imagick;
 
+
+# Set Environment Variables
+ENV DEBIAN_FRONTEND noninteractive
+
+#
+#--------------------------------------------------------------------------
+# Software's Installation
+#--------------------------------------------------------------------------
+#
+# Installing tools and PHP extentions using "apt", "docker-php", "pecl",
+#
+
+# Install "curl", "libmemcached-dev", "libpq-dev", "libjpeg-dev",
+#         "libpng12-dev", "libfreetype6-dev", "libssl-dev", "libmcrypt-dev",
+RUN set -eux; \
+    sed -i 's/^deb /# deb /g' /etc/apt/sources.list; \
+    echo 'deb http://archive.debian.org/debian/ stretch main contrib non-free' >> /etc/apt/sources.list; \
+    apt-get update; \
+    apt-get upgrade -y; \
+    apt-get install -y --no-install-recommends \
+            libmagickwand-dev; \
+    # cleanup
+    rm -rf /var/lib/apt/lists/*
+
+RUN pecl install imagick;
+
 EXPOSE 9000
 CMD ["php-fpm"]
